// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "MacOptimizer",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v12)
    ],
    products: [
        .executable(name: "AppUninstaller", targets: ["AppUninstaller"])
    ],
    targets: [
        .executableTarget(
            name: "AppUninstaller",
            path: "AppUninstaller",
            exclude: [
                "Info.plist",
                "compile_errors.txt",
                "resource"
            ],
            resources: [
                .process("Localizations"),
                .process("AppIcon.icns"),
                .process("ButtonClick.m4a"),
                .process("CleanDidFinish-Winter.m4a"),
                .process("CleanDidFinish.m4a"),
                .process("Intro.mp4"),
                .process("Uninstaller.jpg"),
                .process("Uninstaller@2x.jpg"),
                .process("appuploader.png"),
                .process("updater_module.png"),
                .process("updater_benefit_latest.png"),
                .process("updater_benefit_compatible.png"),
                .process("clean-up.866fafd0.png"),
                .process("deepclean_app_residue.png"),
                .process("deepclean_cache_files.png"),
                .process("deepclean_large_files.png"),
                .process("deepclean_log_files.png"),
                .process("deepclean_system_junk.png"),
                .process("feizhilou.png"),
                .process("mail_attachments_module.png"),
                .process("mail_benefit_disk.png"),
                .process("mail_benefit_envelope.png"),
                .process("large_files_module.png"),
                .process("large_files_benefit_discover.png"),
                .process("large_files_benefit_sort.png"),
                .process("large_files_volume.png"),
                .process("space_lens_module.png"),
                .process("space_lens_benefit_overview.png"),
                .process("space_lens_benefit_decision.png"),
                .process("shredder_module.png"),
                .process("shredder_benefit_secure.png"),
                .process("shredder_benefit_finder.png"),
                .process("malware_module.png"),
                .process("malware_benefit_remove.png"),
                .process("malware_benefit_protect.png"),
                .process("malware_benefit_scan.png"),
                .process("malware_moonlock_logo.png"),
                .process("malware_moonlock_logo_small.png"),
                .process("malware_preferences.png"),
                .process("maintenance_module.png"),
                .process("maintenance_benefit_drive.png"),
                .process("maintenance_benefit_apps.png"),
                .process("maintenance_benefit_search.png"),
                .process("maintenance_free_ram.png"),
                .process("maintenance_purgeable.png"),
                .process("maintenance_dns.png"),
                .process("maintenance_mail.png"),
                .process("maintenance_spotlight.png"),
                .process("maintenance_permissions.png"),
                .process("maintenance_time_machine.png"),
                .process("maintenance_repair_apps.png"),
                .process("extensions_module.png"),
                .process("extensions_benefit_remove.png"),
                .process("extensions_benefit_disable.png"),
                .process("extensions_safari.png"),
                .process("extensions_internet.png"),
                .process("extensions_preferences.png"),
                .process("extensions_spotlight.png"),
                .process("optimization_module.png"),
                .process("optimization_benefit_launch.png"),
                .process("optimization_benefit_running.png"),
                .process("optimization_high_consuming.png"),
                .process("optimization_launch_agents.png"),
                .process("optimization_hung_apps.png"),
                .process("privacy_module.png"),
                .process("privacy_benefit_browse.png"),
                .process("privacy_benefit_chat.png"),
                .process("privacy_permissions.png"),
                .process("trash_bins_module.png"),
                .process("trash_benefit_empty.png"),
                .process("trash_benefit_finder.png"),
                .process("kongjianshentou copy.png"),
                .process("kongjianshentou.png"),
                .process("malware@2x.png"),
                .process("protection.80f7790f.png"),
                .process("resubscribe_welcome.png"),
                .process("resubscribe_welcome@2x.png"),
                .process("shenduqingli.png"),
                .process("smart-scan.2f4ddf59.png"),
                .process("system-junk-mouse.png"),
                .process("system_clean_menu.png"),
                .process("welcome.icns"),
                .process("welcome.png"),
                .process("yibiaopan_2026.png"),
                .process("yinpan_2026.png"),
                .process("yinsi.png"),
                .process("youhua.png"),
                .process("zhiwendunpai_2026.png")
            ]
        ),
        .testTarget(
            name: "AppUninstallerTests",
            dependencies: ["AppUninstaller"]
        )
    ]
)
